### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by domenmerhar** [domenmerhar/pong#1]
- [x] sound effect, 
- [x] music,
- [x] heavy ball,
- [x] fast ball,
- [ ] pause menu,
- [ ] victory screen
- [x] increase speed,
- [x] ball trail,
- [x] add a score sound effect,
- [ ] bloom fast mode,
- [x] add fast small enemy,
- [x] add big slow enemy
